### ISSUE TITLE
Applet should accept CurrencyType's above 0x0002

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-card#27]
https://github.com/GridPlus/phonon-card/blob/f446eadf5e2ac35801e2d9bfed532aa7a4eed88b/Phonon/src/io/gridplus/phonon/PhononApplet.java#L107

https://github.com/GridPlus/phonon-card/blob/f446eadf5e2ac35801e2d9bfed532aa7a4eed88b/Phonon/src/io/gridplus/phonon/PhononApplet.java#L1201

The maximum for currencyType should be the maximum representable uint16 value, not the maximum currently specified currency, 0x02. The LIST_PHONONS command should support filtering on any arbitrary currencyType entered during SET_DESCRIPTOR within the maximum representable boundary. 

Additionally, there seem to be some situations where the check at L1201 listed above that leads to this issue can be accidentally bypassed. Bonus if that bug can be found while removing this limitation on additional currencyTypes.  

I mention this because on my first attempt to reproduce this issue, I was able to setDescriptor and list on a CurrencyType = 0x03, but on subsequent attempts I received an error. Steps to reproduce this error. 
First, add an additional currencyType in model/phonon.go with value = 0x0003 or higher. 
Then, run the following commands to try and setDescriptor with in the repl:
```
go run main/phonon.go repl
unlock
create

created phonon
Key Index:  3
Public Key:  04d184945c0065e7b3ff7016e88cdedf74dba773f6136ec318986a56d87ac14008fb2ffdfe6db5d55560970e0d30c4a796a41ee978b15da8d6507aa20e29cbbddd
04dbd809cc41320d> 

setDescriptor 3 3 10

DEBU[0037] sending SET_DESCRIPTOR command               
DEBU[0037] encoding phonon: KeyIndex: 3
Denomination: 10
currencyType: CurrencyType(3)
PubKey: 
Address: 
CurveType: Secp256k1
SchemaVersion: 0
ExtendedSchemaVersion: 0
ExtendedTLV: [] 
DEBU[0037] raw command before encryption: CLA:  80 Ins:  31 P1:  0 P2:  0 Data: 41 02 00 03 88 01 00 89 01 00 83 01 0A 86 01 00 82 02 00 03 
DEBU[0037] raw command in APDU format: 803100004102000388010089010083010A86010082020003 
DEBU[0037] apdu command hex: 80 31 00 00 30 BF 3F C0 F6 6F 93 DD D7 2B 99 09 C3 1F 10 39 11 6F FD D2 F4 85 3C 71 73 8E 7F 27 4F 02 F8 E1 B9 CA AC 98 4E 8A BA 74 93 1B 45 F0 D5 27 4E 3A 51 
DEBU[0037] apdu response hex: E7 A2 13 D3 7B EF B8 7B E5 23 67 D1 D5 13 99 FC FD 9D FD 2C 2F 77 A5 8E D6 B0 EC BB F8 5A 43 86 90 00 
DEBU[0037] apdu response decrypted hex: 69 84           
ERRO[0037] set descriptor command failed: Phonon does not exist 
could not set descriptor:  Phonon does not exist
```

**Comment by npmaile** [comment]
It can be bypassed if a phonon is created in a mock card, and sent to a production card.

**Comment by npmaile** [comment]
https://github.com/GridPlus/phonon-card/blob/f446eadf5e2ac35801e2d9bfed532aa7a4eed88b/Phonon/src/io/gridplus/phonon/PhononApplet.java#L1200
Probably explains how to get around it. 
If the schema version is 0, the check isn't done.
