### ISSUE TITLE
Card should brick after 10 failed PIN attempts 

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-card#33]
The verifyPIN function should lock the card after 10 failed attempts. It should also report the tries remaining with pin.getTriesRemaining(). Also wondering where that method is being imported as I don't see where the pin class is coming from.

**Comment by SecureElement** [comment]
PIN class is OWNERPin which is an oracle javacard object.  Currently the attempts are set at 3.  Will increase to 10.  Current implementation of failed pin returns the value of (0x63c0 + pin.getTriesRemaining() ).

**Comment by SecureElement** [comment]
Fixed in Mining-Native
