### ISSUE TITLE
Refine Storage of Mined Phonons

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-card#37]
The phonon public key value of the mined phonon should be set to the Hash value which has been checked for it's rarity. This is the value that should be returned to the user. 

The private key value should be set to the random salt which was combined with the card's identity key to create the sha512 hash which was used as the public key. 

Both values should be stored the same as they are created, a 0x04 should NOT be prepended to these values before storage.

**Comment by SecureElement** [comment]
Fixed
