### ISSUE TITLE
SetFriendlyName Causes Memory Overflow Error when input is too long

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-card#48]
This issue is reproduced by the TestSetFriendly name card test. @npmaile to produce a version of that can run on Windows in order to reproduce.

This should be fixed so that subsequent runs of SetFriendlyName and GetFriendlyName succeed despite the bad call to SetFriendlyName.

Additionally, it would be good to understand the consequences of such a memory overflow error for the rest of the program.

**Comment by SecureElement** [comment]
Fixed
