### ISSUE TITLE
MineNativePhonons returns 6F00 memory error after SendPhonons is executed

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-card#54]
The applet can evidently get into an invalid state where all attempts to mine native phonons that otherwise would have been successful return a `6F00` memory error instead. This appears to occur after the applet has executed a SendPhonons command. 

Instructions to reproduce: 
Setup: 
1. Checkout phonon-card branch `debug-mine-6f00`
2. Checkout phonon-client branch `send-phonons-cmd-term-integration`

Execution: 
1. install the card, install cert and init pin. 
2. In client directory: 
`go run main/phonon.go mineNativePhonons -d 2` 
(should eventually successfully mine a phonon, this is the correct behavior)
3. `go run main/phonon.go sendPhonons --mock-receiver -s 0` 
(send a phonon to a mock card via the command line.)
4. `go run main/phonon.go mineNativePhonons -d 2`
(This incorrectly returns a 6F00)

This issue needs to be fixed so that this bad state does not arise. My guess is it has something do with a corruption of the phonon table during Mine and/or Send, or there is some other shared state in Send that is being corrupted.

**Comment by SecureElement** [comment]
Fixed.  issue was with storing 64 byte hash in private key when using a phonon spot that was previously deleted

**Comment by SecureElement** [comment]
fixed
