### ISSUE TITLE
USE_CA_DEMO_KEY should be replaced by ADD_CA command 

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-card#55]
The card's active certificate authority used to validate pairing is currently managed by a boolean variable called USE_CA_DEMO_KEY, which controls whether the secure alpha key, or the insecure demo key is used when building the applet. This works fine in production but causes friction in development since this variable needs to be manually flipped back and forth by developers in the course of day to day development tasks. This frequently leads to devs forgetting to flip it to true, and experiencing mysterious errors, and could also lead to forgetting to flip it to false, and breaking the main branch for production use. 

This could all be avoided by implementing an ADD_CA command, which would allow us to set the CA at first run, instead of at build time. This would get around the lackluster compile tools provided by Javacard for configuring builds, and would also provide a foundation for adding user managed CA's in a multiple trusted manufacturer design.

**Comment by SecureElement** [comment]
Function added to add CA Key. 0x58.
Once Load Certificate is issued, you can not change the CA Key
Please see notes in PR
